/*
Necesito un informe por año , sabor y cantidad
Unir tablas de facturas, items_facturas y tabla_de_productos
*/


-- unión de las tablas 
SELECT P.SABOR, IFa.CANTIDAD, F.FECHA_VENTA FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO;

/* CANTIDAD VENDIDA POR SABOR AÑO 2016 */
-- año de la fecha
-- suma de la cantidad
-- filtrar por fecha 
-- agrupar
-- ordenar por cantidad
SELECT P.SABOR, SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,YEAR(F.FECHA_VENTA) as AÑO FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC;

-- CANTIDAD TOTAL POR AÑO
SELECT  SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,YEAR(F.FECHA_VENTA) as AÑO FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA);



-- RELACION DE CANTIDAD VENDIDA POR SABOR Y CANTIDAD TOTAL VENDIDA POR AÑO 

SELECT * FROM (
SELECT P.SABOR, SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,YEAR(F.FECHA_VENTA) as AÑO FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC
) VENTAS_SABOR
INNER JOIN (
SELECT  SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,YEAR(F.FECHA_VENTA) as AÑO FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_SABOR.AÑO;


-- PORCENTAJES DE LA RELACION
SELECT VENTAS_SABOR.SABOR, VENTAS_SABOR.AÑO , VENTAS_SABOR.CANTIDAD_TOTAL, 
ROUND((VENTAS_SABOR.CANTIDAD_TOTAL/VENTA_TOTAL.CANTIDAD_TOTAL)*100,2) AS PORCENTAJE 
FROM (
SELECT P.SABOR, SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,YEAR(F.FECHA_VENTA) as AÑO FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC
) VENTAS_SABOR
INNER JOIN (
SELECT  SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,YEAR(F.FECHA_VENTA) as AÑO FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_SABOR.AÑO
ORDER BY VENTAS_SABOR.CANTIDAD_TOTAL DESC;



/* 
 VENTAS PORCENTUALES POR TAMAÑO
 Modifica el informe pero ahora para ver el ranking de las ventas por tamaño.

Tips:
Puede parecer difícil pero este es el ejercicio más fácil de resolver.
*/


SELECT VENTAS_TAMANO.TAMANO, VENTAS_TAMANO.AÑO , VENTAS_TAMANO.CANTIDAD_TOTAL, 
ROUND((VENTAS_TAMANO.CANTIDAD_TOTAL/VENTA_TOTAL.CANTIDAD_TOTAL)*100,2) AS PORCENTAJE 
FROM (
SELECT P.TAMANO, SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,YEAR(F.FECHA_VENTA) as AÑO FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.TAMANO, YEAR(F.FECHA_VENTA)
ORDER BY SUM(IFa.CANTIDAD) DESC
) VENTAS_TAMANO
INNER JOIN (
SELECT  SUM(IFa.CANTIDAD) AS CANTIDAD_TOTAL,YEAR(F.FECHA_VENTA) as AÑO FROM 
tabla_de_productos P
INNER JOIN items_facturas IFa
ON P.CODIGO_DEL_PRODUCTO = IFa.CODIGO_DEL_PRODUCTO
INNER JOIN facturas F
ON IFa.NUMERO = F.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_TAMANO.AÑO
ORDER BY VENTAS_TAMANO.CANTIDAD_TOTAL DESC;