USE ventas_jugos;

CREATE TABLE tb_items_facturas(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(20) NOT NULL,
CANTIDAD INT NULL,
PRECIO FLOAT,
PRIMARY KEY (NUMERO, CODIGO)
);


ALTER TABLE  tb_items_facturas ADD CONSTRAINT FK_FACTURA
FOREIGN KEY(NUMERO) REFERENCES tb_factura(NUMERO);

ALTER TABLE  tb_items_facturas ADD CONSTRAINT FK_PRODUCTO
FOREIGN KEY(CODIGO) REFERENCES tb_producto(CODIGO);