/*
	Valor de la secuencia
    ¿Cuál será el valor final de 
    la secuencia tras la ejecución de los siguientes comandos?
*/


CREATE TABLE TAB_IDENTITY2 (
ID INT AUTO_INCREMENT,
DESCRIPTOR VARCHAR(20), 
PRIMARY KEY(ID));

INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE1');

INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE2');

INSERT INTO TAB_IDENTITY2 (DESCRIPTOR) VALUES ('CLIENTE3');

INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE4');

DELETE FROM TAB_IDENTITY2 WHERE ID = 3;

INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE6');

INSERT INTO TAB_IDENTITY2 (ID, DESCRIPTOR) VALUES (NULL, 'CLIENTE7');

DELETE FROM TAB_IDENTITY2 WHERE ID = 2;

SELECT * FROM tab_identity2;